framework:
    messenger:
        serializer:
            default_serializer: App\Component\Symfony\Messenger\Transport\JsonSerializer
        transports:
            app.to.tip: "%env(TIP_USER_EVENT)%"
            ranking.all: "%env(RANKING_ALL_EVENT)%"
            match.to.app: "%env(MATCH_TO_APP)%"

        routing:
            'App\DataTransferObject\TipEventDataProvider':
                - app.to.tip
            'App\DataTransferObject\RankingAllEventDataProvider':
                - ranking.all
            'App\DataTransferObject\MatchListDataProvider':
                - match.to.app
