framework:
    messenger:
        serializer:
            default_serializer: App\Component\Symfony\Messenger\Transport\JsonSerializer
        transports:
            app.to.tip: "%env(TIP_USER_EVENT)%"
            calculation.to.app: "%env(CALCULATION_ALL_EVENT)%"
        routing:
            'App\DataTransferObject\TipEventDataProvider':
                - app.to.tip
            'App\DataTransferObject\RankingAllEventDataProvider':
                - calculation.to.app
