version: '3'

services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - 3336:3306
    redis:
        image: redis:6
        command: redis-server --appendonly yes
        ports:
            - 6379:6379
