tip_controllers:
    resource: ../../src/Component/Tip/Infrastructure/
    type: annotation

user_controllers:
    resource: ../../src/Component/User/Infrastructure/
    type: annotation

user_tips_controllers:
    resource: ../../src/Component/UserTips/Infrastructure/
    type: annotation

user_rating_controllers:
    resource: ../../src/Component/UserRating/Infrastructure/
    type: annotation

game_user_tips_controllers:
    resource: ../../src/Component/GameUserTips/Infrastructure/
    type: annotation
