tip_controllers:
    resource: ../../src/Component/Tip/Infrastructure/
    type: annotation

user_controllers:
    resource: ../../src/Component/User/Infrastructure/
    type: annotation

user_tips_controllers:
    resource: ../../src/Component/UserTips/Infrastructure/
    type: annotation
