# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.redis.uri: '%env(REDIS)%'
    app.env: '%env(APP_ENV)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Component\Tip\Infrastructure\:
        resource: '../src/Component/Tip/Infrastructure/'
        tags: ['controller.service_arguments']

    App\Component\User\Infrastructure\:
        resource: '../src/Component/User/Infrastructure/'
        tags: ['controller.service_arguments']

    App\Component\UserTips\Infrastructure\:
        resource: '../src/Component/UserTips/Infrastructure/'
        tags: [ 'controller.service_arguments' ]

    App\Component\UserRating\Infrastructure\:
        resource: '../src/Component/UserRating/Infrastructure/'
        tags: [ 'controller.service_arguments' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    ###> Xervice\DataProvider ###
    Xervice\DataProvider\Communication\Console\CleanCommand:
        tags: [console.command]
    Xervice\DataProvider\Communication\Console\GenerateCommand:
        tags: [console.command]
    ###< Xervice\DataProvider ###




